# Generated by Django 5.2 on 2025-07-22 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Animal', '0001_initial'),
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_audio', models.FileField(upload_to='grabaciones/')),
                ('fecha', models.DateField()),
                ('investigador', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animal.animal')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ubicacion.ubicacion')),
            ],
        ),
    ]
